version: "3.8"

services:
  web:
    container_name: nextjs-esu
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../.:/app
      - /app/node_modules   # Prevent host from overwriting node_modules
    env_file:
      - ../../docker/dev/dev.env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
