version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"         # Host:Container (you access via http://localhost:3000)
    volumes:
      - .:/app              # Mount your project into the container
      - /app/node_modules   # Prevents overwriting container's node_modules
    command: npm run dev    # Run development server (hot reload)