name: Deploy to main

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read
  packages: write # Needed to push to GitHub Container Registry
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        PROJECT_NAME=$(basename ${{ github.repository }})
        docker build -f docker/live/web/Dockerfile -t ghcr.io/${{ github.repository_owner }}/${PROJECT_NAME}:main . 
      # docker build -t ghcr.io/${{ github.repository_owner }}/${PROJECT_NAME}:main .

    # Push the Docker image
    - name: Push Docker image
      run: |
        PROJECT_NAME=$(basename ${{ github.repository }})
        docker push ghcr.io/${{ github.repository_owner }}/${PROJECT_NAME}:main


  deploy-to-live:
    runs-on: ubuntu-latest
    needs: build-and-push 
    steps:
      - name: Trigger Watchtower via Webhook
        run: |
            curl -X POST "http://165.22.54.114:8090/v1/update?container=esu-web" \
            -H "Authorization: Bearer wt_secret_4aP9tKx7rQm2"


  sonarqube-scan:
    name: sonarqube-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}