name: sonarqube-scan

env:
  TARGET_DIR:

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
  workflow_dispatch:

jobs:
  sonarqube-scan:
    name: sonarqube-scan
    runs-on: ubuntu-latest
    # needs: deploy-to-test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - uses: sonarsource/sonarqube-scan-action@staging
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - uses: sonarsource/sonarqube-quality-gate-action@staging
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
